/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPropsRouteImport } from './routes/_app/props'
import { Route as AppPicksRouteImport } from './routes/_app/picks'
import { Route as AppParlayRouteImport } from './routes/_app/parlay'
import { Route as AppMovementRouteImport } from './routes/_app/movement'
import { Route as AppLinesRouteImport } from './routes/_app/lines'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropsRoute = AppPropsRouteImport.update({
  id: '/props',
  path: '/props',
  getParentRoute: () => AppRoute,
} as any)
const AppPicksRoute = AppPicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => AppRoute,
} as any)
const AppParlayRoute = AppParlayRouteImport.update({
  id: '/parlay',
  path: '/parlay',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementRoute = AppMovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => AppRoute,
} as any)
const AppLinesRoute = AppLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/lines': typeof AppLinesRoute
  '/movement': typeof AppMovementRoute
  '/parlay': typeof AppParlayRoute
  '/picks': typeof AppPicksRoute
  '/props': typeof AppPropsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/lines': typeof AppLinesRoute
  '/movement': typeof AppMovementRoute
  '/parlay': typeof AppParlayRoute
  '/picks': typeof AppPicksRoute
  '/props': typeof AppPropsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lines': typeof AppLinesRoute
  '/_app/movement': typeof AppMovementRoute
  '/_app/parlay': typeof AppParlayRoute
  '/_app/picks': typeof AppPicksRoute
  '/_app/props': typeof AppPropsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/lines'
    | '/movement'
    | '/parlay'
    | '/picks'
    | '/props'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/lines'
    | '/movement'
    | '/parlay'
    | '/picks'
    | '/props'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/lines'
    | '/_app/movement'
    | '/_app/parlay'
    | '/_app/picks'
    | '/_app/props'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/props': {
      id: '/_app/props'
      path: '/props'
      fullPath: '/props'
      preLoaderRoute: typeof AppPropsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/picks': {
      id: '/_app/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof AppPicksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parlay': {
      id: '/_app/parlay'
      path: '/parlay'
      fullPath: '/parlay'
      preLoaderRoute: typeof AppParlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movement': {
      id: '/_app/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof AppMovementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lines': {
      id: '/_app/lines'
      path: '/lines'
      fullPath: '/lines'
      preLoaderRoute: typeof AppLinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLinesRoute: typeof AppLinesRoute
  AppMovementRoute: typeof AppMovementRoute
  AppParlayRoute: typeof AppParlayRoute
  AppPicksRoute: typeof AppPicksRoute
  AppPropsRoute: typeof AppPropsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLinesRoute: AppLinesRoute,
  AppMovementRoute: AppMovementRoute,
  AppParlayRoute: AppParlayRoute,
  AppPicksRoute: AppPicksRoute,
  AppPropsRoute: AppPropsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
